### ISSUE TITLE
Automatically closes

### ISSUE THREAD

**Issue by bullden-id** [JokerDKha/SoS-FoMT#1]
When I double-click SosfmtMsgBin.exe, it automatically closes.
I'm on Windows 10, version 2004.

**Comment by bullden-id** [comment]
It worked!

**Comment by JokerDKha** [comment]
Im just make new easy way to extract and pack:
HOW TO USED:
Extract:
COPY your file text.bin to Folder "file bin here"
Run extract.bat
Pack:
COPY your file text.xml already edited to Folder "file xml here"
Run pack.bat

https://github.com/JokerDKha/SoS-FoMT-Text-Extract-Pack/releases/tag/SoS-FoMT
